Vagrant.configure("2") do |config|

    #Primera máquina virtual
    config.vm.define "vm1" do |vm1|
        #vm1.vm.box = "hashicorp/bionic64"
        #vm1.vm.box = "ubuntu/bionic64"
        vm1.vm.box = "generic/ubuntu2004"
        #vm1.vm.box = "generic/ubuntu2204"
        #vm1.vm.box = "generic/ubuntu1804"
        vm1.vm.hostname = "vm1"
        vm1.vm.network "public_network", ip: "192.168.5.1"

        config.vm.synced_folder "join/", "/home/vagrant"

        vm1.vm.provision "shell", inline: <<-SHELL
            sudo rm script.sh
            echo '#!/bin/bash' >> script.sh
        SHELL

        vm1.vm.provision "shell", inline: <<-SHELL
            sudo apt update
            sudo apt install apt-transport-https ca-certificates curl software-properties-common -y
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
            sudo apt update
            apt-cache policy docker-ce
            sudo apt install docker-ce -y

            sudo docker swarm init --advertise-addr 192.168.5.1 | grep 192 >> script.sh

        SHELL
    end

    #Segunda máquina virtual
    config.vm.define "vm2" do |vm2|
        #vm2.vm.box = "hashicorp/bionic64"
        #vm2.vm.box = "ubuntu/bionic64"
        vm2.vm.box = "generic/ubuntu2004"
        #vm2.vm.box = "generic/ubuntu2204"
        #vm2.vm.box = "generic/ubuntu1804"
        vm2.vm.hostname = "vm2"
        vm2.vm.network "public_network", ip: "192.168.5.2"

        config.vm.synced_folder "join/", "/home/vagrant"

        vm2.vm.provision "shell", inline: <<-SHELL
            sudo apt update
            sudo apt install apt-transport-https ca-certificates curl software-properties-common -y
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
            sudo apt update
            apt-cache policy docker-ce
            sudo apt install docker-ce -y

            sudo bash script.sh
        SHELL
    end
  end