- become: yes
  hosts: all
  name: apache-install
  tasks:
    - name: Wait for apt to unlock
      become: yes
      shell:  while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;

    - name: Install apache2
      apt:        
        name: apache2
        update_cache: yes
        state: latest

    - name: ping .3
      shell: ping 172.16.16.3 >> /var/www/html/index.html &
      async: 30
      poll: 0

    - name: ping .2
      shell: ping 172.16.16.2 >> /var/www/html/index.html &
      async: 30
      poll: 0

  handlers:
    - name: Restart apache2
      service:
        name: apache2
        state: restarted